### ISSUE TITLE
replace is no effect

### ISSUE THREAD

**Issue by feedoom** [romgrk/searchReplace.vim#4]
<img width="1462" alt="searchreplace" src="https://user-images.githubusercontent.com/37018475/122261809-5902ab80-cf07-11eb-93af-6b93d1e975cc.png">

when i replace some word that is no effect

my nvim is 0.5
macos
i has sed and ripgrep

**Comment by romgrk** [comment]
What are you trying to replace?

**Comment by feedoom** [comment]
> What are you trying to replace?

“hello” to replace “word”

**Comment by romgrk** [comment]
Sorry no bandwidth to debug, if it doesn't work for you I'd advise to try a more maintained plugin :/
